baseURL = 'https://maxnagy.com/'
title = 'Max Nagy´s personal Website'
theme = 'terminal' # 'researcher' #'risotto'

author = "Max Nagy"
copyright = "© 2023 Max Nagy"
paginate = 3
languageCode = "en"
DefaultContentLanguage = "en"
#ignoreErrors = ["error-remote-getjson"]

# Automatically add content sections to main menu
sectionPagesMenu = "main"

[params]

[params.theme]
palette = "gruvbox-dark"
mode = "dark-mode"

# Sidebar: about/bio
[params.about]
title = "risotto"
description = "A [hugo](https://gohugo.io) theme inspired by terminal ricing."
logo = "images/rice.svg"

# Sidebar: social links
# Available icon sets:
# * FontAwesome 5 <https://fontawesome.com/> ('fas fa-' or 'fab-fa' for brands)
# * Academicons <https://jpswalsh.github.io/academicons> ('ai ai-')

[[params.socialLinks]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/joeroe/risotto"

[[params.socialLinks]]
icon = "fas fa-envelope"
title = "Email"
url = "mailto:example@example.com"

[menu]

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 10

[taxonomies]
category = "categories"
tag = "tags"
series = "series"

# For hugo >= 0.60.0, enable inline HTML
[markup.goldmark.renderer]
unsafe = true

[privacy]

  [privacy.youtube]
    disabled = false
    privacyEnhanced = true

[languages]
  [languages.en]
    title = "Max Nagy"
    subtitle = "my personal website"

  [languages.en.params.logo]
    logoText = "Max Nagy"
    logoHomeLink = "/"
